image: java:latest

stages:
  - build
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo "Building Jar File"
    - mvn clean install
  artifacts:
    paths:
      - covid-data-server.jar
    expire_in: 1 day

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no covid-data-server.jar $AWS_SERVER:/home/ubuntu/
    - ssh -o StrictHostKeyChecking=no $AWS_SERVER
      "sudo kill -9 \$(ps aux | grep 'covid-data-server.jar' | grep -v 'grep' | awk '{print \$2}');"
    - ssh -o StrictHostKeyChecking=no $AWS_SERVER
      "cd /home/ubuntu; nohup java -jar covid-data-server.jar $PROGRAM_ARGUMENTS < /dev/null > /home/ubuntu/logs/covid-data-server.out 2>&1 &"